import './polyfills.js';

import { WebGLRenderTargetCube } from './renderers/WebGLRenderTargetCube.js';
import { WebGLRenderTarget } from './renderers/WebGLRenderTarget.js';
import { WebGLRenderer } from './renderers/WebGLRenderer.js';
// import { WebGL2Renderer } from './renderers/WebGL2Renderer.js';
import { ShaderLib } from './renderers/shaders/ShaderLib.js';
import { UniformsLib } from './renderers/shaders/UniformsLib.js';
import { UniformsUtils } from './renderers/shaders/UniformsUtils.js';
import { ShaderChunk } from './renderers/shaders/ShaderChunk.js';
import { FogExp2 } from './scenes/FogExp2.js';
import { Fog } from './scenes/Fog.js';
import { Scene } from './scenes/Scene.js';
import { LensFlare } from './objects/LensFlare.js';
import { Sprite } from './objects/Sprite.js';
import { LOD } from './objects/LOD.js';
import { SkinnedMesh } from './objects/SkinnedMesh.js';
import { Skeleton } from './objects/Skeleton.js';
import { Bone } from './objects/Bone.js';
import { Mesh } from './objects/Mesh.js';
import { LineSegments } from './objects/LineSegments.js';
import { LineLoop } from './objects/LineLoop.js';
import { Line } from './objects/Line.js';
import { Points } from './objects/Points.js';
import { Group } from './objects/Group.js';
import { VideoTexture } from './textures/VideoTexture.js';
import { DataTexture } from './textures/DataTexture.js';
import { CompressedTexture } from './textures/CompressedTexture.js';
import { CubeTexture } from './textures/CubeTexture.js';
import { CanvasTexture } from './textures/CanvasTexture.js';
import { DepthTexture } from './textures/DepthTexture.js';
import { Texture } from './textures/Texture.js';
import {} from './geometries/Geometries.js';
import {} from './materials/Materials.js';
import { CompressedTextureLoader } from './loaders/CompressedTextureLoader.js';
import { DataTextureLoader } from './loaders/DataTextureLoader.js';
import { CubeTextureLoader } from './loaders/CubeTextureLoader.js';
import { TextureLoader } from './loaders/TextureLoader.js';
import { ObjectLoader } from './loaders/ObjectLoader.js';
import { MaterialLoader } from './loaders/MaterialLoader.js';
import { BufferGeometryLoader } from './loaders/BufferGeometryLoader.js';
import { DefaultLoadingManager, LoadingManager } from './loaders/LoadingManager.js';
import { JSONLoader } from './loaders/JSONLoader.js';
import { ImageLoader } from './loaders/ImageLoader.js';
import { FontLoader } from './loaders/FontLoader.js';
import { FileLoader } from './loaders/FileLoader.js';
import { Loader } from './loaders/Loader.js';
import { Cache } from './loaders/Cache.js';
import { AudioLoader } from './loaders/AudioLoader.js';
import { SpotLightShadow } from './lights/SpotLightShadow.js';
import { SpotLight } from './lights/SpotLight.js';
import { PointLight } from './lights/PointLight.js';
import { RectAreaLight } from './lights/RectAreaLight.js';
import { HemisphereLight } from './lights/HemisphereLight.js';
import { DirectionalLightShadow } from './lights/DirectionalLightShadow.js';
import { DirectionalLight } from './lights/DirectionalLight.js';
import { AmbientLight } from './lights/AmbientLight.js';
import { LightShadow } from './lights/LightShadow.js';
import { Light } from './lights/Light.js';
import { StereoCamera } from './cameras/StereoCamera.js';
import { PerspectiveCamera } from './cameras/PerspectiveCamera.js';
import { OrthographicCamera } from './cameras/OrthographicCamera.js';
import { CubeCamera } from './cameras/CubeCamera.js';
import { ArrayCamera } from './cameras/ArrayCamera.js';
import { Camera } from './cameras/Camera.js';
import { AudioListener } from './audio/AudioListener.js';
import { PositionalAudio } from './audio/PositionalAudio.js';
import { AudioContext } from './audio/AudioContext.js';
import { AudioAnalyser } from './audio/AudioAnalyser.js';
import { Audio } from './audio/Audio.js';
import { VectorKeyframeTrack } from './animation/tracks/VectorKeyframeTrack.js';
import { StringKeyframeTrack } from './animation/tracks/StringKeyframeTrack.js';
import { QuaternionKeyframeTrack } from './animation/tracks/QuaternionKeyframeTrack.js';
import { NumberKeyframeTrack } from './animation/tracks/NumberKeyframeTrack.js';
import { ColorKeyframeTrack } from './animation/tracks/ColorKeyframeTrack.js';
import { BooleanKeyframeTrack } from './animation/tracks/BooleanKeyframeTrack.js';
import { PropertyMixer } from './animation/PropertyMixer.js';
import { PropertyBinding } from './animation/PropertyBinding.js';
import { KeyframeTrack } from './animation/KeyframeTrack.js';
import { AnimationUtils } from './animation/AnimationUtils.js';
import { AnimationObjectGroup } from './animation/AnimationObjectGroup.js';
import { AnimationMixer } from './animation/AnimationMixer.js';
import { AnimationClip } from './animation/AnimationClip.js';
import { Uniform } from './core/Uniform.js';
import { InstancedBufferGeometry } from './core/InstancedBufferGeometry.js';
import { BufferGeometry } from './core/BufferGeometry.js';
import { GeometryIdCount, Geometry } from './core/Geometry.js';
import { InterleavedBufferAttribute } from './core/InterleavedBufferAttribute.js';
import { InstancedInterleavedBuffer } from './core/InstancedInterleavedBuffer.js';
import { InterleavedBuffer } from './core/InterleavedBuffer.js';
import { InstancedBufferAttribute } from './core/InstancedBufferAttribute.js';
import {} from './core/BufferAttribute.js';
import { Face3 } from './core/Face3.js';
import { Object3D } from './core/Object3D.js';
import { Raycaster } from './core/Raycaster.js';
import { Layers } from './core/Layers.js';
import { EventDispatcher } from './core/EventDispatcher.js';
import { Clock } from './core/Clock.js';
import { QuaternionLinearInterpolant } from './math/interpolants/QuaternionLinearInterpolant.js';
import { LinearInterpolant } from './math/interpolants/LinearInterpolant.js';
import { DiscreteInterpolant } from './math/interpolants/DiscreteInterpolant.js';
import { CubicInterpolant } from './math/interpolants/CubicInterpolant.js';
import { Interpolant } from './math/Interpolant.js';
import { Triangle } from './math/Triangle.js';
import { _Math as Math } from './math/Math.js';
import { Spherical } from './math/Spherical.js';
import { Cylindrical } from './math/Cylindrical.js';
import { Plane } from './math/Plane.js';
import { Frustum } from './math/Frustum.js';
import { Sphere } from './math/Sphere.js';
import { Ray } from './math/Ray.js';
import { Matrix4 } from './math/Matrix4.js';
import { Matrix3 } from './math/Matrix3.js';
import { Box3 } from './math/Box3.js';
import { Box2 } from './math/Box2.js';
import { Line3 } from './math/Line3.js';
import { Euler } from './math/Euler.js';
import { Vector4 } from './math/Vector4.js';
import { Vector3 } from './math/Vector3.js';
import { Vector2 } from './math/Vector2.js';
import { Quaternion } from './math/Quaternion.js';
import { Color } from './math/Color.js';
import { MorphBlendMesh } from './extras/objects/MorphBlendMesh.js';
import { ImmediateRenderObject } from './extras/objects/ImmediateRenderObject.js';
import { VertexNormalsHelper } from './helpers/VertexNormalsHelper.js';
import { SpotLightHelper } from './helpers/SpotLightHelper.js';
import { SkeletonHelper } from './helpers/SkeletonHelper.js';
import { PointLightHelper } from './helpers/PointLightHelper.js';
import { RectAreaLightHelper } from './helpers/RectAreaLightHelper.js';
import { HemisphereLightHelper } from './helpers/HemisphereLightHelper.js';
import { GridHelper } from './helpers/GridHelper.js';
import { PolarGridHelper } from './helpers/PolarGridHelper.js';
import { FaceNormalsHelper } from './helpers/FaceNormalsHelper.js';
import { DirectionalLightHelper } from './helpers/DirectionalLightHelper.js';
import { CameraHelper } from './helpers/CameraHelper.js';
import { BoxHelper } from './helpers/BoxHelper.js';
import { ArrowHelper } from './helpers/ArrowHelper.js';
import { AxisHelper } from './helpers/AxisHelper.js';
import { CatmullRomCurve3 } from './extras/curves/CatmullRomCurve3.js';
import { CubicBezierCurve3 } from './extras/curves/CubicBezierCurve3.js';
import { QuadraticBezierCurve3 } from './extras/curves/QuadraticBezierCurve3.js';
import { LineCurve3 } from './extras/curves/LineCurve3.js';
import { ArcCurve } from './extras/curves/ArcCurve.js';
import { EllipseCurve } from './extras/curves/EllipseCurve.js';
import { SplineCurve } from './extras/curves/SplineCurve.js';
import { CubicBezierCurve } from './extras/curves/CubicBezierCurve.js';
import { QuadraticBezierCurve } from './extras/curves/QuadraticBezierCurve.js';
import { LineCurve } from './extras/curves/LineCurve.js';
import { Shape } from './extras/core/Shape.js';
import { Path } from './extras/core/Path.js';
import { ShapePath } from './extras/core/ShapePath.js';
import { Font } from './extras/core/Font.js';
import { CurvePath } from './extras/core/CurvePath.js';
import { Curve } from './extras/core/Curve.js';
import { ShapeUtils } from './extras/ShapeUtils.js';
import { SceneUtils } from './extras/SceneUtils.js';
import {} from './constants.js';
import {} from './Bonnie3D.Legacy.js';

window.B3D = window.B3D || {};
B3D.WebGLRenderTargetCube = WebGLRenderTargetCube;
B3D.WebGLRenderTarget = WebGLRenderTarget;
B3D.WebGLRenderer = WebGLRenderer;
B3D.ShaderLib = ShaderLib;
B3D.UniformsLib = UniformsLib;
B3D.UniformsUtils = UniformsUtils;
B3D.ShaderChunk = ShaderChunk;
B3D.FogExp2 = FogExp2;
B3D.Fog = Fog;
B3D.Scene = Scene;
B3D.LensFlare = LensFlare;
B3D.Sprite = Sprite;
B3D.LOD = LOD;
B3D.SkinnedMesh = SkinnedMesh;
B3D.Skeleton = Skeleton;
B3D.Bone = Bone;
B3D.Mesh = Mesh;
B3D.LineSegments = LineSegments;
B3D.LineLoop = LineLoop;
B3D.Line = Line;
B3D.Points = Points;
B3D.Group = Group;
B3D.VideoTexture = VideoTexture;
B3D.DataTexture = DataTexture;
B3D.CompressedTexture = CompressedTexture;
B3D.CubeTexture = CubeTexture;
B3D.CanvasTexture = CanvasTexture;
B3D.DepthTexture = DepthTexture;
B3D.Texture = Texture;
B3D.CompressedTextureLoader = CompressedTextureLoader;
B3D.DataTextureLoader = DataTextureLoader;
B3D.CubeTextureLoader = CubeTextureLoader;
B3D.TextureLoader = TextureLoader;
B3D.ObjectLoader = ObjectLoader;
B3D.MaterialLoader = MaterialLoader;
B3D.BufferGeometryLoader = BufferGeometryLoader;
B3D.DefaultLoadingManager = DefaultLoadingManager;
B3D.LoadingManager = LoadingManager;
B3D.JSONLoader = JSONLoader;
B3D.ImageLoader = ImageLoader;
B3D.FontLoader = FontLoader;
B3D.FileLoader = FileLoader;
B3D.Loader = Loader;
B3D.Cache = Cache;
B3D.AudioLoader = AudioLoader;
B3D.SpotLightShadow = SpotLightShadow;
B3D.SpotLight = SpotLight;
B3D.PointLight = PointLight;
B3D.RectAreaLight = RectAreaLight;
B3D.HemisphereLight = HemisphereLight;
B3D.DirectionalLightShadow = DirectionalLightShadow;
B3D.DirectionalLight = DirectionalLight;
B3D.AmbientLight = AmbientLight;
B3D.LightShadow = LightShadow;
B3D.Light = Light;
B3D.StereoCamera = StereoCamera;
B3D.PerspectiveCamera = PerspectiveCamera;
B3D.OrthographicCamera = OrthographicCamera;
B3D.CubeCamera = CubeCamera;
B3D.ArrayCamera = ArrayCamera;
B3D.Camera = Camera;
B3D.AudioListener = AudioListener;
B3D.PositionalAudio = PositionalAudio;
B3D.AudioContext = AudioContext;
B3D.AudioAnalyser = AudioAnalyser;
B3D.Audio = Audio;
B3D.VectorKeyframeTrack = VectorKeyframeTrack;
B3D.StringKeyframeTrack = StringKeyframeTrack;
B3D.QuaternionKeyframeTrack = QuaternionKeyframeTrack;
B3D.NumberKeyframeTrack = NumberKeyframeTrack;
B3D.ColorKeyframeTrack = ColorKeyframeTrack;
B3D.BooleanKeyframeTrack = BooleanKeyframeTrack;
B3D.PropertyMixer = PropertyMixer;
B3D.PropertyBinding = PropertyBinding;
B3D.KeyframeTrack = KeyframeTrack;
B3D.AnimationUtils = AnimationUtils;
B3D.AnimationObjectGroup = AnimationObjectGroup;
B3D.AnimationMixer = AnimationMixer;
B3D.AnimationClip = AnimationClip;
B3D.Uniform = Uniform;
B3D.InstancedBufferGeometry = InstancedBufferGeometry;
B3D.BufferGeometry = BufferGeometry;
B3D.GeometryIdCount = GeometryIdCount;
B3D.Geometry = Geometry;
B3D.InterleavedBufferAttribute = InterleavedBufferAttribute;
B3D.InstancedInterleavedBuffer = InstancedInterleavedBuffer;
B3D.InterleavedBuffer = InterleavedBuffer;
B3D.InstancedBufferAttribute = InstancedBufferAttribute;
B3D.Face3 = Face3;
B3D.Object3D = Object3D;
B3D.Raycaster = Raycaster;
B3D.Layers = Layers;
B3D.EventDispatcher = EventDispatcher;
B3D.Clock = Clock;
B3D.QuaternionLinearInterpolant = QuaternionLinearInterpolant;
B3D.LinearInterpolant = LinearInterpolant;
B3D.DiscreteInterpolant = DiscreteInterpolant;
B3D.CubicInterpolant = CubicInterpolant;
B3D.Interpolant = Interpolant;
B3D.Triangle = Triangle;
B3D.Math = Math;
B3D.Spherical = Spherical;
B3D.Cylindrical = Cylindrical;
B3D.Plane = Plane;
B3D.Frustum = Frustum;
B3D.Sphere = Sphere;
B3D.Ray = Ray;
B3D.Matrix4 = Matrix4;
B3D.Matrix3 = Matrix3;
B3D.Box3 = Box3;
B3D.Box2 = Box2;
B3D.Line3 = Line3;
B3D.Euler = Euler;
B3D.Vector4 = Vector4;
B3D.Vector3 = Vector3;
B3D.Vector2 = Vector2;
B3D.Quaternion = Quaternion;
B3D.Color = Color;
B3D.MorphBlendMesh = MorphBlendMesh;
B3D.ImmediateRenderObject = ImmediateRenderObject;
B3D.VertexNormalsHelper = VertexNormalsHelper;
B3D.SpotLightHelper = SpotLightHelper;
B3D.SkeletonHelper = SkeletonHelper;
B3D.PointLightHelper = PointLightHelper;
B3D.RectAreaLightHelper = RectAreaLightHelper;
B3D.HemisphereLightHelper = HemisphereLightHelper;
B3D.GridHelper = GridHelper;
B3D.PolarGridHelper = PolarGridHelper;
B3D.FaceNormalsHelper = FaceNormalsHelper;
B3D.DirectionalLightHelper = DirectionalLightHelper;
B3D.CameraHelper = CameraHelper;
B3D.BoxHelper = BoxHelper;
B3D.ArrowHelper = ArrowHelper;
B3D.AxisHelper = AxisHelper;
B3D.CatmullRomCurve3 = CatmullRomCurve3;
B3D.CubicBezierCurve3 = CubicBezierCurve3;
B3D.QuadraticBezierCurve3 = QuadraticBezierCurve3;
B3D.LineCurve3 = LineCurve3;
B3D.ArcCurve = ArcCurve;
B3D.EllipseCurve = EllipseCurve;
B3D.SplineCurve = SplineCurve;
B3D.CubicBezierCurve = CubicBezierCurve;
B3D.QuadraticBezierCurve = QuadraticBezierCurve;
B3D.LineCurve = LineCurve;
B3D.Shape = Shape;
B3D.Path = Path;
B3D.ShapePath = ShapePath;
B3D.Font = Font;
B3D.CurvePath = CurvePath;
B3D.Curve = Curve;
B3D.ShapeUtils = ShapeUtils;
B3D.SceneUtils = SceneUtils;